version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "80:3000"
    restart: always
    container_name: prep-legacy
